name: Care-Central

on: push

jobs:
    Care-Central:
        name: Test code base
        run-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run Super-Linter
              uses: github/super-linter@4
              env:
                DEFAULT_BRANCH: main
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}