name: Care Central

on:
  push:
    branches: ["main"]

jobs:
  test:
   name: Testing the code
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run the code
      uses: npm test