name: Jest testing

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test_using_jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensures repo is available

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust to your project's Node.js version

      - name: Install Dependencies
        run: npm install  # Ensures all dependencies are installed
        working-directory: Care-Central/React

      - name: Run Jest Tests
        uses: willcaul/jest-github-action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: npm test
          working-directory: Care-Central/React
